/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ict_ish_MainActivity */

#ifndef _Included_edu_hit_ict_ish_MainActivity
#define _Included_edu_hit_ict_ish_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_hit_ict_ish_MainActivity_CAMERA_WITH_DATA
#define edu_hit_ict_ish_MainActivity_CAMERA_WITH_DATA 3023L
#undef edu_hit_ict_ish_MainActivity_PHOTO_PICKED_WITH_DATA
#define edu_hit_ict_ish_MainActivity_PHOTO_PICKED_WITH_DATA 3021L
#undef edu_hit_ict_ish_MainActivity_MAX_SECRET_MESSAGE_LENGTH
#define edu_hit_ict_ish_MainActivity_MAX_SECRET_MESSAGE_LENGTH 102400L
#undef edu_hit_ict_ish_MainActivity_MAX_SECRET_FILE_SIZE
#define edu_hit_ict_ish_MainActivity_MAX_SECRET_FILE_SIZE 2097152L
/*
 * Class:     edu_hit_ict_ish_MainActivity
 * Method:    analyzeJpegStegInfo
 * Signature: (Ljava/lang/String;Ledu/hit/ict/ish/JpegStegInfo;)Ledu/hit/ict/ish/JpegStegInfo;
 */
JNIEXPORT jobject JNICALL Java_edu_hit_ict_ish_MainActivity_analyzeJpegStegInfo
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     edu_hit_ict_ish_MainActivity
 * Method:    stegJpegMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ict_ish_MainActivity_stegJpegMessage
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     edu_hit_ict_ish_MainActivity
 * Method:    extractJpegMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_hit_ict_ish_MainActivity_extractJpegMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_hit_ict_ish_MainActivity
 * Method:    stegJpegFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ict_ish_MainActivity_stegJpegFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     edu_hit_ict_ish_MainActivity
 * Method:    extractJpegFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ict_ish_MainActivity_extractJpegFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
