/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ict_ish_imgsteg_ExtractActivity */

#ifndef _Included_edu_hit_ict_ish_imgsteg_ExtractActivity
#define _Included_edu_hit_ict_ish_imgsteg_ExtractActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ict_ish_imgsteg_ExtractActivity
 * Method:    extractJpegFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_hit_ict_ish_imgsteg_ExtractActivity_extractJpegFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
