/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_hit_ict_ish_imgsteg_StegActivity */

#ifndef _Included_edu_hit_ict_ish_imgsteg_StegActivity
#define _Included_edu_hit_ict_ish_imgsteg_StegActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hit_ict_ish_imgsteg_StegActivity
 * Method:    stegJpegFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_hit_ict_ish_imgsteg_StegActivity_stegJpegFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
